language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - yasm
    - libx11-xcb-dev
    - libglu1-mesa-dev
    - libboost1.55-dev
    - libx264-dev

script: "./autogen.sh && ./configure --enable-debug CXX='g++-4.9' && make && make check"

notifications:
  slack: keithw:2nINWkhRQ60BzeTDNYXgpLkU
